# Generated by Django 5.1.6 on 2025-05-25 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Backup name/identifier', max_length=255)),
                ('backup_type', models.CharField(choices=[('full', 'Full System Backup'), ('database', 'Database Only'), ('media', 'Media Files Only'), ('settings', 'Settings Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(help_text='Path to backup file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('includes_database', models.BooleanField(default=True)),
                ('includes_media', models.BooleanField(default=True)),
                ('includes_settings', models.BooleanField(default=True)),
                ('database_records', models.IntegerField(blank=True, help_text='Number of database records', null=True)),
                ('media_files_count', models.IntegerField(blank=True, help_text='Number of media files', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this backup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('full', 'Full System Backup'), ('database', 'Database Only'), ('media', 'Media Files Only'), ('settings', 'Settings Only')], default='full', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('includes_database', models.BooleanField(default=True)),
                ('includes_media', models.BooleanField(default=True)),
                ('includes_settings', models.BooleanField(default=True)),
                ('compress_backup', models.BooleanField(default=True)),
                ('keep_backups', models.IntegerField(default=10, help_text='Number of backups to keep')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Schedule',
                'verbose_name_plural': 'Backup Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('restore_database', models.BooleanField(default=True)),
                ('restore_media', models.BooleanField(default=True)),
                ('restore_settings', models.BooleanField(default=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('backup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='backup.backuprecord')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pre_restore_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_restore_for', to='backup.backuprecord')),
            ],
            options={
                'verbose_name': 'Restore Record',
                'verbose_name_plural': 'Restore Records',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
